ext {
    extName = 'Master Extension'
    extClass = '.MasterExtension'
    extVersionCode = 5
}

apply plugin: "kei.plugins.extension.legacy"

android {
    packaging {
        resources {
            pickFirsts += [
                'META-INF/nanohttpd/mimetypes.properties',
                'META-INF/nanohttpd/default-mimetypes.properties'
            ]
        }
    }
}

dependencies {
    implementation(project(':lib:playlistutils'))
    implementation(project(':lib:unpacker'))
    implementation(project(':lib:cloudflareinterceptor'))
    implementation(project(':lib:megacloudextractor'))
    implementation(project(':lib:cryptoaes'))
    implementation(project(":lib:rapidcloudextractor"))
    implementation(project(":lib:gogostreamextractor"))
    implementation(project(':lib:streamwishextractor'))
    implementation(project(':lib:vidmolyextractor'))
    implementation(project(':lib:streamlareextractor'))
    implementation(project(':lib:mp4uploadextractor'))
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:okruextractor'))
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:m3u8server'))
    implementation(project(':lib-multisrc:anikototheme'))
    implementation(project(':lib:vidhideextractor'))
    
    // 🎯 Single NanoHTTPD version that works for everything now!
    implementation("com.github.komikku-app.nanohttpd:nanohttpd:gradle-upgrade-SNAPSHOT")
}
