ext {
    extName = 'Master Extension'
    extClass = '.MasterExtension'
    extVersionCode = 5
}

apply plugin: "kei.plugins.extension.legacy"

// Handles duplicate META-INF files between the two NanoHTTPD forks
android {
    packaging {
        resources {
            pickFirsts += ['META-INF/nanohttpd/mimetypes.properties']
        }
    }
}

dependencies {
    implementation(project(':lib:playlistutils'))
    implementation(project(':lib:unpacker'))
    implementation(project(':lib:cloudflareinterceptor'))
    implementation(project(':lib:megacloudextractor'))
    implementation(project(':lib:cryptoaes'))
    implementation(project(":lib:rapidcloudextractor"))
    implementation(project(":lib:gogostreamextractor"))
    implementation(project(':lib:streamwishextractor'))
    implementation(project(':lib:vidmolyextractor'))
    implementation(project(':lib:streamlareextractor'))
    implementation(project(':lib:mp4uploadextractor'))
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:okruextractor'))
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:m3u8server'))
    implementation(project(':lib-multisrc:anikototheme'))
    
    // 1. AnimePahe needs the 'fi.iki.elonen' package
    implementation("com.github.NanoHttpd.nanohttpd:nanohttpd:nanohttpd-project-2.3.1")
    
    // 2. Anikoto / M3U8Server needs the newer 'org.nanohttpd' package
    implementation("com.github.NanoHttpd.nanohttpd:nanohttpd:-SNAPSHOT")
}
